version: '3.8'

services:
    backend:
        build: ./backend
        ports:
            - "9001:9001"
            - "9002:9002"

    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
